line-length = 100

exclude = [
    "__pycache__",
    ".eggs",
    ".git",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "_build",
    "build",
    "dist",
    "migrations",
]

[format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
docstring-code-format = true
